fix for vim

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -6,7 +6,7 @@ install_cmake() {
   local concurrency=$3
 
   if [ "$TMPDIR" = "" ]; then
-    local tmp_download_dir=$(mktemp -d -t kitware_cmake_build_XXXXXX)
+    local tmp_download_dir=$(mktemp -d -t asdf_vim_build_XXXXXX)
   else
     local tmp_download_dir=$TMPDIR
   fi
@@ -19,26 +19,16 @@ install_cmake() {
   # running this in subshell
   # we don't want to disturb current working dir
   (
-    if ! type "unzip" &> /dev/null; then
-      echo "ERROR: unzip not found"
+    if ! type "tar" &> /dev/null; then
+      echo "ERROR: tar not found"
       exit 1
     fi
 
-    unzip -q $source_path -d $tmp_download_dir || exit 1
-    cd $tmp_download_dir/CMake-${version}
-    if [ -d "$QTBINDIR" ]; then
-      PATH=$PATH:$QTBINDIR ./bootstrap --prefix=$install_path --qt-gui -- -DCMAKE_BUILD_TYPE=Release
-    else
-      ./bootstrap --prefix=$install_path -- -DCMAKE_BUILD_TYPE=Release
-    fi
-    make -j $concurrency
+    tar -xvf $source_path -C $tmp_download_dir || exit 1
+    cd $tmp_download_dir/vim-${version}
+    # configure with $install_path
+    make
     make install
-
-    if [ -d "$install_path/CMake.app/Contents" ]; then
-      mkdir "$install_path/bin"
-      cd "$install_path/bin"
-      ln -s ../CMake.app/Contents/bin/* .
-    fi
   )
 
 }
@@ -56,7 +46,7 @@ get_download_file_path() {
   local version=$1
   local tmp_download_dir=$2
 
-  echo "$tmp_download_dir/kitware-cmake-${version}.zip"
+  echo "$tmp_download_dir/vim-${version}.tar.gz"
 }
 
 get_download_url() {
@@ -64,10 +54,10 @@ get_download_url() {
 
   if [[ "$version" =~ ^[0-9]+\.* ]] ; then
     # if version is a release number, prepend v
-    echo "https://github.com/Kitware/CMake/archive/v${version}.zip"
+    echo "https://github.com/vim/vim/archive/v${version}.tar.gz"
   else
     # otherwise it can be a branch name or commit sha
-    echo "https://github.com/Kitware/CMake/archive/${version}.zip"
+    echo "https://github.com/vim/vim/archive/${version}.tar.gz"
   fi
 }
 
